#ifndef _ABIBITS_ERRNO_H
#define _ABIBITS_ERRNO_H

#define ENOSYS      	1
#define ENOENT      	2
#define ENOTDIR     	3
#define EEXIST      	4
#define ENODEV      	5
#define ENOEXEC     	6
#define EAGAIN      	7
#define EACCES      	8
#define EIO         	9
#define ESRCH       	10
#define ERANGE      	11
#define ENOMEM      	12
#define EINTR       	13
#define EPERM       	14
#define ETIMEDOUT   	15
#define EBUSY       	16
#define ENOTSUP     	17
#define ECHILD      	18
#define ECONNREFUSED 	19
#define EBADF       	20
#define EDEADLK     	21
#define EINVAL      	22
#define ECONNRESET  	23
#define ENOTCONN    	24
#define EPIPE       	25
#define EFAULT      	26
#define EOVERFLOW   	27
#define EISDIR      	28
#define ESPIPE      	29
#define ENXIO       	30
#define EDOM            31
#define EILSEQ          32
#define E2BIG           33
#define EADDRINUSE      34
#define ENOTSOCK        35
#define ENAMETOOLONG    36
#define EADDRNOTAVAIL   37
#define EALREADY        38
#define EBADMSG         39
#define ECANCELED       40
#define ECONNABORTED    41
#define EDESTADDRREQ    42
#define EDQUOT          43
#define EFBIG           44
#define EHOSTUNREACH    45
#define EIDRM           46
#define EINPROGRESS     47
#define EISCONN         48
#define EMFILE          49
#define EMLINK          50
#define EMSGSIZE        51
#define EMULTIHOP       52
#define ENETDOWN        53
#define ENETRESET       54
#define ENETUNREACH     55
#define ENFILE          56
#define ENOBUFS         57
#define ENOLINK         58
#define ENOMSG          59
#define ENOPROTOOPT     60
#define ENOTEMPTY       61
#define ENOTTY          62
#define ENOTRECOVERABLE 63
#define EOPNOTSUPP      64
#define EOWNERDEAD      65
#define EPROTO          66
#define EPROTONOSUPPORT 67
#define EPROTOTYPE      68
#define EROFS           69
#define ESTALE          70
#define ETXTBSY         71
#define EXDEV           72
#define ENODATA         73
#define ETIME           74
#define ENOKEY          75
#define ESHUTDOWN       76
#define EHOSTDOWN       77
#define EBADFD          78
#define ENOMEDIUM       79
#define ENOTBLK         80
#define ENONET          81
#define EPFNOSUPPORT    82
#define ESTRPIPE        83
#define ERFKILL         84
#define EREMOTEIO       85
#define EBADR           86
#define EMEDIUMTYPE     87
#define EUNATCH         88
#define EKEYREJECTED    89
#define EUCLEAN         90
#define EBADSLT         91
#define EREMOTE         92
#define ENOANO          93
#define ENOCSI          94
#define ENOSTR          95
#define ETOOMANYREFS    96
#define ENOPKG          97
#define EKEYREVOKED     98
#define EXFULL          99
#define ELNRNG          100
#define ENOTUNIQ        101
#define ERESTART        102
#define EUSERS          103
#define ELOOP           104
#define ENOLCK          105
#define ESOCKTNOSUPPORT 106
#define EWOULDBLOCK     107
#define EAFNOSUPPORT    108
#define ENOSPC          109

#endif
